BOOKS WITH EXACTLY ONE COPY
SELECT * FROM Books WHERE Available_Copies = 1;

AUTORS WHOSE NAME START WITH A LETTER
SELECT * FROM Authors WHERE Author_Name like 'J%';

LIST MEMBERS WITH NO ADDRESS RECORDED
SELECT * FROM members WHERE address IS NULL;

LIST BORROWINGS ON A SPECIFIC DATE
SELECT * FROM borrowings WHERE borrowing_date = TO_DATE('2025-10-01', 'YYYY-MM-DD');

LIST BOOKS WITH PUBLICATION YEAR AFTER 2000
SELECT * FROM books WHERE publication_year >2000;

LIST BORROWING WITH NO FINES
SELECT * FROM borrowings WHERE fine = 0 ;

LIST MEMBERS SORTED BY MEMBERSHIP DATES
SELECT * FROM members ORDER BY membership_date DESC;

COUNT THE TOTAL NUMBER OF AUTHORS
SELECT COUNT(*) AS totalcount from authors;

LIST BOOKS WITH TITLE CONTAINING A CERTAIN WORD
SELECT * FROM books where title LIKE '%POTTER%';

LIST BORROWINGS RETURNED ON A CERTAIN DATE
SELECT * FROM borrowings where return_date = TO_DATE('2025-10-10', 'YYYY-MM-DD');

LIST MEMBERS WITH A SPECIFIC ARE CODE IN THEIR PHONE NUMBER
SELECT * FROM members where phone LIKE '111%';

LIST BOOKS SORTED ALPHABETICALLY
SELECT * FROM books ORDER BY book_title;

SUM THE TOTAL AVAILABLE COPIES ACROSS ALL BOOKS
SELECT SUM(Available_copies) as sumofnumberofbooks FROM BOOKS ;

LIST ALL BORROWINGS WITH A DUE DATE FROM A SPECIFIC MONTH
SELECT * FROM borrowings where EXTRACT(MONTH FROM due_date) =5;

LIST AUTHORS WITH THEIR NAMES LONGER THAN 10 CHARACTERS
SELECT * FROM authors where LENGTH(author_name)>10;
